language: csharp
mono: latest
dotnet: 1.0.4
dist: trusty

solution: src/GitTools.Testing.sln
sudo: false
install:
  - nuget install xunit.runner.console -Version 2.1.0 -OutputDirectory ./src/packages
script:
  - dotnet build ./src/ -c:Debug
  - dotnet test ./src/GitTools.Testing.Tests/ -c:Debug --no-build --framework netcoreapp2.2
# Disable testing against .NET 4.5.2 through Mono because it tries to resolve
# the Windows libgit binary instead of the linux one.
#  - mono --debug --runtime=v4.0.30319 ./src/packages/xunit.runner.console.2.1.0/tools/xunit.console.exe ./src/GitTools.Testing.Tests/bin/Debug/net452/GitTools.Testing.Tests.dll
